steps:

- id: 'Instalando o go'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['GOPATH=.']

- id: "Rodando o teste"
  name: 'gcr.io/cloud-builders/go'
  args: ['test']
  env: ['GOPATH=.']

- id: "Criando o container"
  name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--build-arg'
  - 'version=1.0.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/calcular-edicao:1.0.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/calcular-edicao:latest'
  - '.'

images: 
- 'gcr.io/$PROJECT_ID/calcular-edicao:latest'
- 'gcr.io/$PROJECT_ID/calcular-edicao:1.0.0'