steps:

# - id: 'Instalando o go'
#   name: 'gcr.io/cloud-builders/go'
#   args: ['install', '/src/calcular-edicao']
#   env: ['GOPATH=.']

- id: "Rodando o teste"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '/src/calcular-edicao']
  env: ['GOPATH=.']

- id: "Criando o container"
  name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--build-arg'
  - 'version=1.0.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/calcular-edicao:1.0.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/calcular-edicao:latest'
  - '.'

images: 
- 'gcr.io/$PROJECT_ID/calcular-edicao:latest'
- 'gcr.io/$PROJECT_ID/calcular-edicao:1.0.0'