steps:

# - id: 'Instalando o go'
#   name: 'gcr.io/cloud-builders/go'
#   args: ['install', 'go/src']
#   env: ['PROJECT_ROOT=calcular-adicao']

- id: "Rodando o teste"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '.']
  env: ['PROJECT_ROOT=src/calcular-adicao']

- id: "Criando o container"
  name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '--build-arg'
  - 'version=1.0.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/calcular-adicao:1.0.0'
  - '-t'
  - 'gcr.io/$PROJECT_ID/calcular-adicao:latest'
  - '.'

images: 
- 'gcr.io/$PROJECT_ID/calcular-adicao:latest'
- 'gcr.io/$PROJECT_ID/calcular-adicao:1.0.0'